# Compose used for production

version: '3.5'

services:

  frontend_prod:
    image: registry.gitlab.com/analytics-ufcg/agora-digital-frontend:release-prod
    networks:
      - traefik_web
    labels:
      - "traefik.backend=leggo_frontend"
      - "traefik.docker.network=traefik_web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:leggo.org.br,www.leggo.org.br"
      - "traefik.port=80"

networks:
  traefik_web:
    external: true
